### ISSUE TITLE
 Todo List

### ISSUE THREAD

**Issue by UsefSalim** [UsefSalim/mongoDB#1]
- [x] Importer le fichier json ci-joint dans votre base de données. 
- [x] Afficher les films de l’année 2010 
- [x] Combien de film a été réalisé en 2009. 
- [x] Faites une requête pour récupérer des documents des films réalisés en 2008 en excluant les champs :
- _id, cast, genres. 
- [x] Afficher tous les films commençant par la lettre A.
- [x] Afficher les films où ‘Timothy Gibbs’ a joué en 2011 
- [x] Afficher les films de type ‘Thriller’ en 2011
- [x]  Afficher les films de type ‘Thriller’ réalisés en 2016 par ordre alphabétique inverse de leurs ‘title’
- [x] Insérer deux film de votre choix dans la base en utilisant un BulkWrite ( pour le champs ‘year’, il doit être 2020)
- [x] Supprimer tous les films réalisés avant 2000
- [x] Ajouter un champs rating qui sera de type array d’objets pour tous les documents
- [x]  Faites vous et un collaborateur, les ratings (le rating est sur 5) de deux films de votre choix, comme suit : ratings: [ { by: "moi", rating: 4 }, {by:"collaborateur”, rating: 5} ]
- [x]  Créer un champ qui sera la moyenne de tous les ratings est appelé le : ar
- [x] Renommer le champ créer précédémment à savoir : ar, pour devenir averageRating.
- [x]  Créer un champs views qui sera un array qui contiendra des valeurs comme ci-après : ‘views ‘:[123444, 66855,78966]
- [x] Faites une mise à jour des films que vous avez insérer en renseignant les valeurs pour le tableau views. 
- [x] Créer un champs totalViews qui sera la somme du tableau view
- [x]  Créer un champs budget pour tous les documents et initialiser sa valeur à -1
- [x]  Modifier les valeurs budget pour les films que vous avez ajouté. 
- [x] Faites la mise à jour des films que vous avez ajouté précédemment. 
- [x] Faites un back up de votre base de données.

**Comment by said11707** [comment]
j'ai pas réussi d'exécuter les nombres de film 2009 rappelle moi de la commande

**Comment by said11707** [comment]
> 
> 
> j'ai pas réussi d'exécuter les nombres de film 2009 rappelle moi de la commande

j'ai trouvé ... db.movies.find({year:2009}).count()    == 229

**Comment by UsefSalim** [comment]
> db.movies.find({year:2010}).pretty()    /// 
> db.movies.find({year:2009}).count() => 229
> db.movies.find({year:2008},{_id:1,cast:1,genres:1})
> db.movies.find({ "title": { $regex: /^A/ } })
> db.movies.find({cast:"Timothy Gibbs",year:2011}).pretty()
>  db.movies.find({genres:"Thriller",year:2011}).pretty()
>  db.movies.find({genres:"Thriller",year:2016}).sort({title:-1}).pretty()
> BulkWrite   ???
>  db.movies.deleteMany({year:{$lt:2000}})
> db.movies.updateMany({}, {$set: {"rating": []}})
> db.movies.updateMany({_id:ObjectId("60084a39dd80d2427818b6df"),_id:ObjectId("60084a39dd80d2427818b6dd")}, {$set: {rating:[ { by: "moi", rating: 4 }, {by:"collaborateur", rating: 5} ]}})
> db.movies.updateMany({}, {$set: {"ar":""}})
> db.movies.updateMany({},{$rename:{"ar":"averageRating"}})

**Comment by said11707** [comment]
BulkWrit------> db.movies.insert([{title: "Beginners","year":2020}, {title:"beng testa","year":2020}]);

**Comment by said11707** [comment]
C' est quoi la différence si j'ai fait db.movies.remove({"year":2000});
Ou db.movies.deleteMany({year:{$lt:2000}}) ??
parceque quand j'ai fait db.movies.deleteMany({year:{$lt:2000}})  il a garder les film on 2000 .
mais quand j'ai fait db.movies.remove({"year":2000}); il a appliqué la notion indiqueé dans le brife on suppriment tout les film on 2000

**Comment by said11707** [comment]
je crois que tu doit faire {$eq: 2000} à la place de {$lt: 2000}.
si je me trompe expliqué moi Mrc

**Comment by UsefSalim** [comment]
la question dit supprimer tout les filme realisé avant 2000 alor 2000 n'est pas inclue alor le $lt veux dire less than (i.e. <)   et le remouveMany surrimme tout les filme qui correspondent a la condition

**Comment by said11707** [comment]
un petit astuce :
 Il est assez lourd de devoir taper à chaque fois <<db.movies.commande>>, la console Mongo est aussi un shell JavaScript, il est donc tout à fait possible d’enregistrer des choses dans des variables !  
Exemple:
// on enregistre la collection dans une variable
s = db.movies

// nous pouvons maintenant faire comme ceci
s.find().pretty()

**Comment by said11707** [comment]
J'ai créer un champs views qui sera un array qui contiendra des valeurs comme  ‘views':[123444, 66855,78966]
Avec la commende :  m.insert({}, { "views":[123444, 66855,78966]}]
m= db.movies
